# -*- coding: utf-8 -*-
"""compute_vision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4xilWyuWouPY8EzJ99h8BUMQ3A8UA6m
"""

import tensorflow as tf

mnist = tf.keras.datasets.fashion_mnist;

(training_images,training_labels),(test_images,test_labels)  = mnist.load_data();
#load_data method will divide mnist into training ,testing data and training_images will be array size of [28][28]

#normalizing
training_images  = training_images / 255.0
test_images = test_images / 255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])


model.compile(optimizer = tf.train.AdamOptimizer(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)